### ISSUE TITLE
窗口设计师启动失败

### ISSUE THREAD

**Issue by blackvccat** [duolabmeng6/GoEasyDesigner#7]
[unplugin-vue-components] component "Button"(C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Button/Button.vue) has naming conflicts with other components, ignored.
    [unplugin-vue-components] component "ButtonAttr"(C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Button/ButtonAttr.vue) has naming conflicts with other components, ignored.
    [unplugin-vue-components] component "Switch"(C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Switch/Switch.vue) has naming conflicts with other components, ignored.
    [unplugin-vue-components] component "SwitchAttr"(C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Switch/SwitchAttr.vue) has naming conflicts with other components, ignored.
    [vite:vue] [@vue/compiler-sfc] "item" is a destructured prop and should not be passed directly to watch(). Pass a getter () => item instead.

    C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/RenderDesignComponent.vue
    153|  let timerId;
    154|
    155|  watch(item, (newValue, oldValue) => {
       |        ^^^^
    156|    clearTimeout(timerId);
    157|    timerId = setTimeout(() => {
    file: C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/RenderDesignComponent.vue
    error during build:
    Error: [@vue/compiler-sfc] "item" is a destructured prop and should not be passed directly to watch(). Pass a getter () => item instead.

    C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/src/components/RenderDesignComponent.vue
    153|  let timerId;
    154|
    155|  watch(item, (newValue, oldValue) => {
       |        ^^^^
    156|    clearTimeout(timerId);
    157|    timerId = setTimeout(() => {
        at ScriptCompileContext.error (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:15730:11)
        at checkUsage (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19853:13)
        at Object.enter (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19868:7)
        at SyncWalker.visit (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:116:17)
        at SyncWalker.visit (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:153:12)
        at SyncWalker.visit (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:146:19)
        at Object.walk (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:322:19)   
        at transformDestructuredProps (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19862:16)
        at Object.compileScript (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:20479:5)
        at resolveScript (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:349:31)       
        at genScriptCode (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:2545:18)      
        at transformMain (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:2355:54)      
        at Object.transform (C:\Users\blackvccat\Desktop\wails-template-vue-go-easy-main\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:2881:16)   
        at file:///C:/Users/blackvccat/Desktop/wails-template-vue-go-easy-main/GoEasyDesigner/GoEasyDesigner/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25544:40

**Comment by duolabmeng6** [comment]
你是在运行源码吗

**Comment by blackvccat** [comment]
> 你是在运行源码吗
> 

对的

**Comment by blackvccat** [comment]
> 你是在运行源码吗
> 

demo成功运行出来了窗口但是第二个文件失败了

**Comment by blackvccat** [comment]
> 你是在运行源码吗


C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner>wails dev  
Wails CLI v2.9.1

Updating go.mod to use Wails 'v2.9.1'
Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > eview@0.0.0 build
    > vite build

    vite v4.5.5 building for production...
    transforming...
    ✓ 92 modules transformed.
    ✓ built in 1.82s

    [unplugin-vue-components] component "Button"(C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Button/Button.vue) has naming conflicts with other components, ignored.
    [unplugin-vue-components] component "ButtonAttr"(C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Button/ButtonAttr.vue) has naming conflicts with other components, ignored.
    [unplugin-vue-components] component "Switch"(C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Switch/Switch.vue) has naming conflicts with other components, ignored.
    [unplugin-vue-components] component "SwitchAttr"(C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/boxs/td/Switch/SwitchAttr.vue) has naming conflicts with other components, ignored.
    [vite:vue] [@vue/compiler-sfc] "item" is a destructured prop and should not be passed directly to watch(). Pass a getter () => item instead.

    C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/RenderDesignComponent.vue
    153|  let timerId;
    154|
    155|  watch(item, (newValue, oldValue) => {
       |        ^^^^
    156|    clearTimeout(timerId);
    157|    timerId = setTimeout(() => {
    file: C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/RenderDesignComponent.vue
    error during build:
    Error: [@vue/compiler-sfc] "item" is a destructured prop and should not be passed directly to watch(). Pass a getter () => item instead.

    C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/src/components/RenderDesignComponent.vue
    153|  let timerId;
    154|
    155|  watch(item, (newValue, oldValue) => {
       |        ^^^^
    156|    clearTimeout(timerId);
    157|    timerId = setTimeout(() => {
        at ScriptCompileContext.error (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:15730:11)
        at checkUsage (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19853:13)
        at Object.enter (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19868:7)
        at SyncWalker.visit (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:116:17)
        at SyncWalker.visit (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:153:12)
        at SyncWalker.visit (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:146:19)
        at Object.walk (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\estree-walker\dist\umd\estree-walker.js:322:19)
        at transformDestructuredProps (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19862:16)
        at Object.compileScript (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:20479:5)
        at resolveScript (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:349:31)
        at genScriptCode (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:2545:18)
        at transformMain (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:2355:54)
        at Object.transform (C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner\frontend\node_modules\@vitejs\plugin-vue\dist\index.cjs:2881:16)
        at file:///C:/Users/blackvccat/Desktop/cat/GoEasyDesigner/GoEasyDesigner/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25544:40


  ERROR   exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

C:\Users\blackvccat\Desktop\cat\GoEasyDesigner\GoEasyDesigner>

**Comment by duolabmeng6** [comment]
看起来，感觉是vue的问题，前段时间我才更新过啊，等我有空再运行一下看看。

**Comment by duolabmeng6** [comment]
vite版本感觉你的很高啊

**Comment by duolabmeng6** [comment]
4.5.5 不知道是不是这个问题了 等有空我去试一下 不过前段时间我才更新了1次

**Comment by duolabmeng6** [comment]
![image](https://github.com/user-attachments/assets/ba0dc29d-8304-4dcd-ae55-ab1ebe789916)  我就说你的vite版本高了...

**Comment by duolabmeng6** [comment]
我定的vite是4.5.3
你用的4.5.5版本不对 也可能vue版本不对
你按照我仓库的依赖安装
pnpm i 
这样子装速度快

**Comment by blackvccat** [comment]
> 我定的vite是4.5.3
> 你用的4.5.5版本不对 也可能vue版本不对
> 你按照我仓库的依赖安装
> pnpm i 
> 这样子装速度快

感谢了我去试试估计可以解决

**Comment by duolabmeng6** [comment]
一般用 vfox这种node环境管理的软件
